name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        ruby-version: ['2.7', '3.0', '3.1', 'head']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false

      - name: Install dependencies
        run: bundle install

      - name: Tests
        run: bundle exec gd
